### PR TITLE
Fix documentation and error messages

### LINKED ISSUE #172: [PE-D][Tester B] Error message not consistent
when inputting the command `add-i-task n/name i/0 e/2023-12-12`

the message given is `Index is not a non-zero unsigned integer.`

whereas when inputting the command `mark-a 0`

The message given is `Invalid command format! 
mark-a: Marks an assignment as completed, identified by the index number used in the displayed assignments list.Parameters: INDEX (must be a positive integer)
Example: mark-a 1`

Maybe these same types of errors could give the same message

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: antonTan96/ped#3

### LINKED ISSUE #183: [PE-D][Tester D] Discrepancy between UG and app for editing
### Description

UG states `edit-i-role i/INDEX d/DESCRIPTION` as the input for the `Editing an internship task` command. However, on the app, the `edit-i-role i/INDEX` can be paired with other field tags to edit other fields. Perhaps indicating the optional fields in the UG will be more accurate.

### Steps to reproduce

1. Add internship role
1. Call `edit-i-role i/1 p/200`

### Expected outcome

* Error message

### Actual outcome

* Success message
* Internship role is edited

### Screenshot

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: tllshan/ped#9

### PR DESCRIPTION
**Pull request by jrchoo**
1. Fix #183 [[PE-D][Tester D] Discrepancy between UG and app for editing](https://github.com/AY2324S1-CS2103T-T12-3/tp/issues/183)
2. Fix #172 [[PE-D][Tester B] Error message not consistent](https://github.com/AY2324S1-CS2103T-T12-3/tp/issues/172)

### CODE REVIEW

**Review by Badatprogrammiing — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/internship/task/AddInternshipTaskCommand.java [hunk 1]
```diff
@@ -43,7 +43,7 @@ public class AddInternshipTaskCommand extends InternshipCommand {
             + "[" + PREFIX_OUTCOME + "awaiting/follow-up/ghosted/rejected/offered" + "]\n"
             + "[" + PREFIX_TAG + "TAG" + "]\n"
             + "Example: " + COMMAND_WORD
-            + " add-a n/Assignment 1 d/description e/2023-12-18 19:00 p/2023-08-19 18:00 t/group s/incomplete";
+            + " add-a n/Assignment i/1 d/description e/2023-12-18 19:00 p/2023-08-19 18:00 t/group s/incomplete";
```
Comment (Badatprogrammiing) [inline src/main/java/seedu/address/logic/commands/internship/task/AddInternshipTaskCommand.java:46]: add-a is wrong

Comment (Badatprogrammiing) [reply src/main/java/seedu/address/logic/commands/internship/task/AddInternshipTaskCommand.java:46]: should not have p/ as well

File: docs/UserGuide.md [hunk 2]
```diff
@@ -549,6 +549,17 @@ To view internship role parameter information, click [here](#internship-role-par
 
 **Purpose:** Edit the specified parameters of a specified internship role.
 
+<div markdown="block" class="alert alert-info">
+
+**Note:**
+
+- The index refers to the index number in the displayed internship role list. If you want to find out the index of the
+  internship role you want to edit, you can use ``list-i`` to view all the current internship roles you have.
+- While the various parameters `[c/CYCLE] [d/DESCRIPTION] [p/PAY] [o/OUTCOME] [l/LOCATION]` are optional, you should
```
Comment (Badatprogrammiing) [inline docs/UserGuide.md:558]: should -> need to

**Review by Badatprogrammiing — APPROVED** [review]
